#!/bin/bash

DISTRO=`cat /etc/*-release | grep ^ID= | tr "=" "\n" | grep -v ^ID | grep -o '\w*'`
NAMESPACE=centos
[[ $DISTRO =~ rhel* ]] && NAMESPACE=rhscl

echo "This is a S2I ${DISTRO} base image:" > /opt/app-root/static/index.html

cat <<EOF
Script di usage customizzato, non sta facendo nulla oltre a stampare questo messaggio

EOF