FROM ubi8/ubi:latest

LABEL maintainer=Luca

RUN yum install -y httpd && \
    yum clean all

RUN sed -ri -e "/^Listen 80/c\Listen 8080" /etc/httpd/conf/httpd.conf && \
    chown -R apache:apache /etc/httpd/logs/ && \
    chown -R apache:apache /run/httpd/ && \
    chown -R apache:apache /var/www/html

ENV IMAGE-PNG topolino.png
EXPOSE 8080
USER apache
ADD https://www.extraordy.com/ /var/www/html/index.html
WORKDIR /var/www/html
COPY topolino.png topolino.png
ENTRYPOINT ["httpd"]
CMD ["-D", "FOREGROUND"]
# sh ENTRYPOINT CMD
# sh httpd -D FOREGROUND
# ENTRYPOINT ["httpd", "-D", "FOREGROUND"]
# sh ENTRYPOINT
# CMD ["httpd", "-D", "FOREGROUND"]
# sh CMD
# podman run img NEW_CMD
# sh ENTRYPOINT NEW_CMD
# CMD ["mysql"]
# podman run mysql bash
